# Generated by Django 3.0 on 2026-05-28 16:42

from django.db import migrations

def copy_profile():
    old_profile = apps.get.model('oc_lettings_site','Profile')
    new_profile = apps.get.model('Profiles','Profile')

    for old_object in old_profile.objects.all():
        new_profile.objects.create(
            user = old_object.user
            favorite_city = old_object.favorite_city
        )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
       migrations.RunPython(copy_profile)
    ]
