# Generated by Django 3.0 on 2026-05-28 16:42

from django.db import migrations


def copy_lettings(apps, schema_editor):
    old_letting = apps.get_model("oc_lettings_site", "Address")
    new_letting = apps.get_model("letting", "Address")

    for old_object in old_letting.objects.all():
        new_letting.objects.create(
            number=old_object.number,
            street=old_object.street,
            city=old_object.city,
            state=old_object.state,
            zip_code=old_object.zip_code,
            country_iso_code=old_object.country_iso_code,
        )

    old_letting = apps.get_model("oc_lettings_site", "Letting")
    new_letting = apps.get_model("letting", "Letting")

    for old_object in old_letting.objects.all():
        new_letting.objects.create(
            title=old_object.title, address_id=old_object.address_id
        )


class Migration(migrations.Migration):

    dependencies = [
        ("letting", "0001_initial"),
        ("oc_lettings_site", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(copy_lettings),
    ]
