# Generated by Django 3.0 on 2026-06-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letting', '0002_copy_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
